// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Run from "./Run.js";
import * as Repl from "./Repl.js";
import * as Belt_List from "../../../node_modules/rescript/lib/es6/belt_List.js";

var args = Belt_List.fromArray(Deno.args);

function help(param) {
  console.log("\n  repl                 Start the REPL\n  run [file.alma]      Run [file.alma]\n");
  
}

if (args) {
  switch (args.hd) {
    case "repl" :
        if (args.tl) {
          console.log("\n  repl                 Start the REPL\n  run [file.alma]      Run [file.alma]\n");
        } else {
          Repl.run(undefined);
        }
        break;
    case "run" :
        var match = args.tl;
        if (match && !match.tl) {
          Run.file(match.hd);
        } else {
          console.log("\n  repl                 Start the REPL\n  run [file.alma]      Run [file.alma]\n");
        }
        break;
    default:
      console.log("\n  repl                 Start the REPL\n  run [file.alma]      Run [file.alma]\n");
  }
} else {
  console.log("\n  repl                 Start the REPL\n  run [file.alma]      Run [file.alma]\n");
}

export {
  args ,
  help ,
  
}
/* args Not a pure module */
