// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Repl from "./Repl.js";

var args = Deno.args;

function help(param) {
  console.log("\n  repl            Start the REPL\n");
  
}

if (args.length !== 1) {
  console.log("\n  repl            Start the REPL\n");
} else {
  var match = args[0];
  if (match === "repl") {
    Repl.run(undefined);
  } else {
    console.log("\n  repl            Start the REPL\n");
  }
}

export {
  args ,
  help ,
  
}
/* args Not a pure module */
