// Generated by ReScript, PLEASE EDIT WITH CARE


function make(value, firstToken, lastToken) {
  return {
          value: value,
          start: firstToken.position,
          end: lastToken.position + lastToken.lexeme.length | 0
        };
}

var $$String;

export {
  $$String ,
  make ,
  
}
/* No side effect */
