// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Test from "./Test.js";
import * as Curry from "../../../node_modules/rescript/lib/es6/curry.js";
import * as Parser from "./Parser.js";
import * as Tokenizer from "./Tokenizer.js";
import * as Belt_Array from "../../../node_modules/rescript/lib/es6/belt_Array.js";
import * as Belt_Option from "../../../node_modules/rescript/lib/es6/belt_Option.js";
import * as AssertsTs from "https://deno.land/std@0.97.0/testing/asserts.ts";

Test.suite("Parser", (function (param) {
        var test = param.test;
        var testCases = [
          [
            "123",
            {
              TAG: 0,
              _0: {
                value: {
                  TAG: 1,
                  _0: 123.0,
                  [Symbol.for("name")]: "Number"
                },
                start: 0,
                end: 3
              },
              [Symbol.for("name")]: "Ok"
            }
          ],
          [
            "123.2",
            {
              TAG: 0,
              _0: {
                value: {
                  TAG: 1,
                  _0: 123.2,
                  [Symbol.for("name")]: "Number"
                },
                start: 0,
                end: 5
              },
              [Symbol.for("name")]: "Ok"
            }
          ],
          [
            "true",
            {
              TAG: 0,
              _0: {
                value: {
                  TAG: 0,
                  _0: true,
                  [Symbol.for("name")]: "Bool"
                },
                start: 0,
                end: 4
              },
              [Symbol.for("name")]: "Ok"
            }
          ],
          [
            "false",
            {
              TAG: 0,
              _0: {
                value: {
                  TAG: 0,
                  _0: false,
                  [Symbol.for("name")]: "Bool"
                },
                start: 0,
                end: 5
              },
              [Symbol.for("name")]: "Ok"
            }
          ],
          [
            "variableOne",
            {
              TAG: 0,
              _0: {
                value: {
                  TAG: 3,
                  _0: "variableOne",
                  [Symbol.for("name")]: "Identifier"
                },
                start: 0,
                end: 11
              },
              [Symbol.for("name")]: "Ok"
            }
          ],
          [
            "variable_one",
            {
              TAG: 0,
              _0: {
                value: {
                  TAG: 3,
                  _0: "variable_one",
                  [Symbol.for("name")]: "Identifier"
                },
                start: 0,
                end: 12
              },
              [Symbol.for("name")]: "Ok"
            }
          ],
          [
            "espaÆàʥñÑol",
            {
              TAG: 0,
              _0: {
                value: {
                  TAG: 3,
                  _0: "espaÆàʥñÑol",
                  [Symbol.for("name")]: "Identifier"
                },
                start: 0,
                end: 11
              },
              [Symbol.for("name")]: "Ok"
            }
          ],
          [
            "\"😄\"",
            {
              TAG: 0,
              _0: {
                value: {
                  TAG: 2,
                  _0: "😄",
                  [Symbol.for("name")]: "String"
                },
                start: 0,
                end: 4
              },
              [Symbol.for("name")]: "Ok"
            }
          ],
          [
            "\"\n\"",
            {
              TAG: 0,
              _0: {
                value: {
                  TAG: 2,
                  _0: "\n",
                  [Symbol.for("name")]: "String"
                },
                start: 0,
                end: 3
              },
              [Symbol.for("name")]: "Ok"
            }
          ],
          [
            "\"\"",
            {
              TAG: 0,
              _0: {
                value: {
                  TAG: 2,
                  _0: "",
                  [Symbol.for("name")]: "String"
                },
                start: 0,
                end: 2
              },
              [Symbol.for("name")]: "Ok"
            }
          ],
          [
            "(\"\")",
            {
              TAG: 0,
              _0: {
                value: {
                  TAG: 2,
                  _0: "",
                  [Symbol.for("name")]: "String"
                },
                start: 1,
                end: 3
              },
              [Symbol.for("name")]: "Ok"
            }
          ],
          [
            "(((1)))",
            {
              TAG: 0,
              _0: {
                value: {
                  TAG: 1,
                  _0: 1.0,
                  [Symbol.for("name")]: "Number"
                },
                start: 3,
                end: 4
              },
              [Symbol.for("name")]: "Ok"
            }
          ],
          [
            "(((1))",
            {
              TAG: 1,
              _0: [{
                  message: "1:6: Expected ')' after parenthesized expression, but instead found: '[End of file]'\n\n  1│ (((1))\n   │ ↑",
                  token: {
                    kind: /* Eof */38,
                    lexeme: "[End of file]",
                    position: 5,
                    line: 1,
                    column: 6
                  }
                }],
              [Symbol.for("name")]: "Error"
            }
          ],
          [
            "(((1))))",
            {
              TAG: 1,
              _0: [{
                  message: "1:7: Expected the end of input, but instead found: ')'\n\n  1│ (((1))))\n   │        ↑",
                  token: {
                    kind: /* RightParen */1,
                    lexeme: ")",
                    position: 7,
                    line: 1,
                    column: 7
                  }
                }],
              [Symbol.for("name")]: "Error"
            }
          ]
        ];
        return Belt_Array.forEachWithIndex(testCases, (function (i, param) {
                      var expected = param[1];
                      var input = param[0];
                      return Curry._2(test, "" + i, (function (param) {
                                    var tokens = Tokenizer.parse(input);
                                    if (tokens.TAG === /* Ok */0) {
                                      var actual = Parser.parse(input, tokens._0);
                                      if (!AssertsTs.equal(actual, expected)) {
                                        console.log("\n", JSON.stringify(JSON.parse(Belt_Option.getExn(JSON.stringify(actual))), null, 4));
                                      }
                                      AssertsTs.assertEquals(actual, expected, "");
                                      return ;
                                    }
                                    var ss = Belt_Array.map(tokens._0, (function (a) {
                                            return a.message;
                                          }));
                                    ss.splice(0, 0, "Error tokenizing test input");
                                    AssertsTs.fail(ss.join("\n\n"));
                                    
                                  }));
                    }));
      }));

export {
  
}
/*  Not a pure module */
