// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Compiler from "./Compiler.js";

function run(param) {
  console.log("alma repl.\n  .exit      Exit the repl session\n");
  var _param;
  while(true) {
    var input = prompt(">");
    if (input !== undefined) {
      switch (input) {
        case "" :
            _param = undefined;
            continue ;
        case ".exit" :
            console.log("👋");
            return ;
        default:
          var e = Compiler.compile(input);
          console.log(e._0);
          _param = undefined;
          continue ;
      }
    } else {
      console.log("👋");
      return ;
    }
  };
}

export {
  run ,
  
}
/* Compiler Not a pure module */
