// Generated by ReScript, PLEASE EDIT WITH CARE

import * as $$File from "./File.js";
import * as Curry from "../../../node_modules/rescript/lib/es6/curry.js";
import * as Compiler from "./Compiler.js";

function file(path) {
  var __x = Curry._1($$File.read, path);
  __x.then(function (input) {
        var e = Compiler.compile(input);
        console.log(e._0);
        return Promise.resolve(undefined);
      });
  
}

export {
  file ,
  
}
/* File Not a pure module */
