// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "../../../node_modules/rescript/lib/es6/curry.js";

function suite(scope, testFn) {
  return Curry._1(testFn, {
              test: (function (subject, fn) {
                  Deno.test(scope + ": " + subject, fn);
                  
                }),
              testAsync: (function (subject, fn) {
                  Deno.test(scope + ": " + subject, fn);
                  
                })
            });
}

export {
  suite ,
  
}
/* No side effect */
