// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


function exprToString(expr) {
  if (typeof expr === "number") {
    return "()";
  }
  switch (expr.TAG | 0) {
    case /* Bool */0 :
        if (expr._0) {
          return "true";
        } else {
          return "false";
        }
    case /* Number */1 :
        return String(expr._0);
    case /* String */2 :
        return "\"" + expr._0 + "\"";
    case /* Identifier */3 :
        return expr._0;
    case /* Lambda */4 :
        return expr._0 + " => " + exprToString(expr._1.value);
    case /* FnCall */5 :
        return exprToString(expr._0.value) + "(" + exprToString(expr._1.value) + ")";
    case /* Let */6 :
        return "let " + expr._0 + " = " + exprToString(expr._1.value) + "; " + exprToString(expr._2.value);
    
  }
}

exports.exprToString = exprToString;
/* No side effect */
