// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


function exprToString(expr) {
  if (typeof expr === "number") {
    return "()";
  }
  switch (expr.TAG | 0) {
    case /* Identifier */0 :
        return expr._0;
    case /* Lambda */1 :
        return "λ" + expr._0 + ". " + exprToString(expr._1);
    case /* FnCall */2 :
        return "(" + exprToString(expr._0) + " " + exprToString(expr._1) + ")";
    case /* Let */3 :
        return "let " + expr._0 + " = " + exprToString(expr._1) + " in " + exprToString(expr._2);
    
  }
}

exports.exprToString = exprToString;
/* No side effect */
