// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Repl = require("./Repl.js");
var InferTest = require("./InferTest.js");

var args = (process.argv.slice(2));

function help(param) {
  console.log("\n  repl            Start the REPL\n  compiler-tests  Run the compiler tests\n");
  
}

if (args.length !== 1) {
  console.log("\n  repl            Start the REPL\n  compiler-tests  Run the compiler tests\n");
} else {
  var match = args[0];
  switch (match) {
    case "compiler-tests" :
        InferTest.run(undefined);
        break;
    case "repl" :
        Repl.run(undefined);
        break;
    default:
      console.log("\n  repl            Start the REPL\n  compiler-tests  Run the compiler tests\n");
  }
}

exports.args = args;
exports.help = help;
/* args Not a pure module */
