// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


function make(value, firstToken, lastToken) {
  return {
          value: value,
          start: firstToken.position,
          end: lastToken.position + lastToken.lexeme.length | 0
        };
}

var $$String;

exports.$$String = $$String;
exports.make = make;
/* No side effect */
