// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Readline = require("readline");

function make(param) {
  return Readline.createInterface({
              input: process.stdin,
              output: process.stdout,
              prompt: "> "
            });
}

function question(rl, q, onAnswer) {
  rl.question(q, onAnswer);
  
}

function close(prim) {
  prim.close();
  
}

exports.make = make;
exports.question = question;
exports.close = close;
/* readline Not a pure module */
