// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Belt_MapString = require("rescript/lib/js/belt_MapString.js");

function empty(param) {
  
}

var getExn = Belt_MapString.getExn;

exports.empty = empty;
exports.getExn = getExn;
/* No side effect */
